### ISSUE TITLE
running= npm i node-red-contrib-http-event-collector

### ISSUE THREAD

**Issue by ScadaSplunker** [gdziuba/http-event-collector#6]
I am getting this error when running the following 
npm i node-red-contrib-http-event-collector
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/splunk/splunk-javascript-logging.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: Logfile

I get the same error when trying from the Node red palette. Any help appreciated.

**Comment by ScadaSplunker** [comment]
24 verbose node v12.18.3
25 verbose npm  v6.14.8

**Comment by gdziuba** [comment]
Node has been updated.
